<#
.SYNOPSIS
  Install / manage the Pi Speak gateway as an auto-starting, self-restarting background task.

.DESCRIPTION
  Makes the headless gateway come up automatically at log on and stay up (keep-alive via
  gateway-supervisor.ps1), so it's always reachable over Tailscale (e.g. http://<tailscale-ip>:8767)
  and the OMP / agent hub can be driven from the phone/Boox app without manually starting anything.

  Two install methods, tried in order (no admin required for the fallback):
    1. Scheduled Task "PiSpeakGateway" at log on (preferred; also restarts if the task dies).
    2. Per-user Startup-folder entry (PiSpeakGateway.vbs, launches the supervisor hidden) -- used
       automatically when registering a scheduled task is denied (non-elevated session).
  Either way the supervisor runs as the current user, so the gateway keeps the user's PATH,
  Tailscale auth, and omp/codex/claude/pi CLI profiles.

.PARAMETER Action
  install | uninstall | start | stop | restart | status   (default: status)

.EXAMPLE
  powershell -NoProfile -ExecutionPolicy Bypass -File scripts\gateway-autostart.ps1 install
#>
[CmdletBinding()]
param(
  [Parameter(Position = 0)]
  [ValidateSet('install', 'uninstall', 'start', 'stop', 'restart', 'status')]
  [string]$Action = 'status',
  [int]$Port = 8767
)

$ErrorActionPreference = 'Stop'
$repo = Split-Path -Parent $PSScriptRoot
$supervisor = Join-Path $PSScriptRoot 'gateway-supervisor.ps1'
$TaskName = 'PiSpeakGateway'
$startupDir = Join-Path $env:APPDATA 'Microsoft\Windows\Start Menu\Programs\Startup'
$startupVbs = Join-Path $startupDir 'PiSpeakGateway.vbs'

function Test-GatewayHealthy {
  try { return ((Invoke-RestMethod -Uri ("http://127.0.0.1:{0}/health" -f $Port) -TimeoutSec 3).app -eq 'pi-speak') }
  catch { return $false }
}
function Get-GatewayProcesses {
  Get-CimInstance Win32_Process -Filter "Name='node.exe'" -ErrorAction SilentlyContinue |
    Where-Object { $_.CommandLine -and $_.CommandLine -match 'headless-gateway\.js' }
}
function Get-SupervisorProcesses {
  Get-CimInstance Win32_Process -ErrorAction SilentlyContinue |
    Where-Object { $_.CommandLine -and $_.CommandLine -match 'gateway-supervisor\.ps1' }
}
function Stop-Everything {
  foreach ($p in Get-SupervisorProcesses) { try { Stop-Process -Id $p.ProcessId -Force -ErrorAction Stop } catch {} }
  foreach ($p in Get-GatewayProcesses)   { try { Stop-Process -Id $p.ProcessId -Force -ErrorAction Stop } catch {} }
}
function Wait-Healthy([int]$Seconds = 30) {
  for ($i = 0; $i -lt $Seconds; $i++) { if (Test-GatewayHealthy) { return $true }; Start-Sleep -Seconds 1 }
  return $false
}
function Get-ListeningPid {
  $c = Get-NetTCPConnection -State Listen -LocalPort $Port -ErrorAction SilentlyContinue | Select-Object -First 1
  if ($c) { return $c.OwningProcess } else { return $null }
}
function Start-SupervisorNow {
  Start-Process -FilePath 'powershell.exe' `
    -ArgumentList ('-NoProfile -NonInteractive -WindowStyle Hidden -ExecutionPolicy Bypass -File "{0}"' -f $supervisor) `
    -WorkingDirectory $repo -WindowStyle Hidden | Out-Null
}
function Install-StartupEntry {
  New-Item -ItemType Directory -Force -Path $startupDir | Out-Null
  $cmd = 'powershell.exe -NoProfile -NonInteractive -WindowStyle Hidden -ExecutionPolicy Bypass -File ""{0}""' -f $supervisor
  $vbs = @"
' Auto-generated by gateway-autostart.ps1 -- launches the Pi Speak gateway supervisor hidden at log on.
CreateObject("WScript.Shell").Run "$cmd", 0, False
"@
  Set-Content -Path $startupVbs -Value $vbs -Encoding ascii
}
function Remove-StartupEntry { if (Test-Path $startupVbs) { Remove-Item $startupVbs -Force } }

switch ($Action) {
  'install' {
    if (-not (Test-Path (Join-Path $repo 'dist\headless-gateway.js'))) {
      Write-Output "WARNING: dist\headless-gateway.js not found. Run 'npm run build' in $repo first."
    }
    Write-Output "Stopping any existing gateway so the keep-alive owns a single instance..."
    Stop-Everything
    Start-Sleep -Milliseconds 800

    $method = $null
    try {
      $arg = '-NoProfile -NonInteractive -WindowStyle Hidden -ExecutionPolicy Bypass -File "{0}"' -f $supervisor
      $taskAction = New-ScheduledTaskAction -Execute 'powershell.exe' -Argument $arg -WorkingDirectory $repo
      $taskTrigger = New-ScheduledTaskTrigger -AtLogOn
      $taskSettings = New-ScheduledTaskSettingsSet -AllowStartIfOnBatteries -DontStopIfGoingOnBatteries `
        -StartWhenAvailable -RestartCount 999 -RestartInterval (New-TimeSpan -Minutes 1) `
        -ExecutionTimeLimit ([TimeSpan]::Zero) -MultipleInstances IgnoreNew
      $taskPrincipal = New-ScheduledTaskPrincipal -UserId ("{0}\{1}" -f $env:USERDOMAIN, $env:USERNAME) `
        -LogonType Interactive -RunLevel Limited
      Register-ScheduledTask -TaskName $TaskName -Action $taskAction -Trigger $taskTrigger -Settings $taskSettings `
        -Principal $taskPrincipal -Description 'Pi Speak headless gateway (auto-start + keep-alive)' -Force | Out-Null
      Start-ScheduledTask -TaskName $TaskName
      $method = 'scheduled task (At Log On)'
    } catch {
      Write-Output ("Scheduled task registration unavailable ({0}); using per-user Startup entry instead." -f $_.Exception.Message)
      Install-StartupEntry
      Start-SupervisorNow
      $method = "Startup entry ($startupVbs)"
    }

    if (Wait-Healthy 30) {
      Write-Output ("OK: auto-start installed via {0}. Gateway healthy on port {1} (PID {2})." -f $method, $Port, (Get-ListeningPid))
    } else {
      Write-Output ("Installed via {0}, but gateway not healthy yet -- check %LOCALAPPDATA%\pi-speak\logs\gateway-supervisor.log" -f $method)
    }
  }

  'uninstall' {
    Stop-Everything
    $did = @()
    if (Get-ScheduledTask -TaskName $TaskName -ErrorAction SilentlyContinue) {
      try { Unregister-ScheduledTask -TaskName $TaskName -Confirm:$false; $did += 'scheduled task' } catch { Write-Output ("Could not remove scheduled task: {0}" -f $_.Exception.Message) }
    }
    if (Test-Path $startupVbs) { Remove-StartupEntry; $did += 'Startup entry' }
    if ($did.Count) { Write-Output ("Removed {0}; stopped the gateway." -f ($did -join ' + ')) }
    else { Write-Output "Nothing installed; stopped any running gateway." }
  }

  'start' {
    if (Get-ScheduledTask -TaskName $TaskName -ErrorAction SilentlyContinue) { Start-ScheduledTask -TaskName $TaskName }
    else { Start-SupervisorNow }
    if (Wait-Healthy 30) { Write-Output ("Started. Gateway healthy on port {0} (PID {1})." -f $Port, (Get-ListeningPid)) }
    else { Write-Output "Started, but gateway not healthy yet -- check the supervisor log." }
  }

  'stop' {
    Stop-Everything
    Write-Output "Stopped the gateway and its supervisor (auto-start brings it back at next log on, or run 'start')."
  }

  'restart' {
    Stop-Everything; Start-Sleep -Milliseconds 800
    if (Get-ScheduledTask -TaskName $TaskName -ErrorAction SilentlyContinue) { Start-ScheduledTask -TaskName $TaskName }
    else { Start-SupervisorNow }
    if (Wait-Healthy 30) { Write-Output ("Restarted. Gateway healthy on port {0} (PID {1})." -f $Port, (Get-ListeningPid)) }
    else { Write-Output "Restart issued, but gateway not healthy yet -- check the supervisor log." }
  }

  'status' {
    $task = Get-ScheduledTask -TaskName $TaskName -ErrorAction SilentlyContinue
    if ($task) { $auto = "scheduled task ({0})" -f (Get-ScheduledTask -TaskName $TaskName).State }
    elseif (Test-Path $startupVbs) { $auto = 'Startup entry' }
    else { $auto = 'NOT installed' }
    $listenPid = Get-ListeningPid
    Write-Output ("Auto-start     : {0}" -f $auto)
    Write-Output ("Supervisor     : {0} running" -f @(Get-SupervisorProcesses).Count)
    Write-Output ("Gateway health : {0} (port {1}{2})" -f $(if (Test-GatewayHealthy) { 'healthy' } else { 'down' }), $Port, $(if ($listenPid) { ", PID $listenPid" } else { '' }))
    try {
      $ip = (& "$env:ProgramFiles\Tailscale\tailscale.exe" ip -4 2>$null | Select-Object -First 1)
      if ($ip) { Write-Output ("Tailscale URL  : http://{0}:{1}  (reach this from the app)" -f $ip.Trim(), $Port) }
    } catch {}
  }
}
